### ISSUE TITLE
Support for Quip?

### ISSUE THREAD

**Issue by Mark-H** [modmore/Akismet#6]
To my surprise, [it appears QuipReply also runs preHooks](https://github.com/modxcms/Quip/blob/develop/core/components/quip/processors/web/comment/create.php#L90). So maybe we could also add support for that in a future release - I've got Quip setup on my personal site if a test bed is needed. Not that there's a lot of posts going on there, but..

[Code of quipHooks](https://github.com/modxcms/Quip/blob/develop/core/components/quip/model/quip/quiphooks.class.php) looks virtually identical to that of loginHooks so maaaaaaaaybe we just need to check for it in Akismet::getFields/setError?

**Comment by muzzwood** [comment]
It's a little different. It needs to be run on a postHook or the values aren't available, and the config needs to be taken from the Quip class rather than the hook.
addError is the same for all 3 hook types.

Done with this: https://github.com/modmore/Akismet/commit/31203f6a01492491fea347e1f784ea0ba8390e7a

**Comment by muzzwood** [comment]
Running as a postHook meant it was too late to block the form going through... I worked around values not being available in the preHook by getting them directly from the post.

**Comment by Mark-H** [comment]
So it should be added to the preHooks then, right?

**Comment by muzzwood** [comment]
Yup, correct!
